/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LangSelect: typeof import('./../components/common/LangSelect.vue')['default']
    PressFeedback: typeof import('./../components/base/PressFeedback.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/base/SearchBar.vue')['default']
    StatusPage: typeof import('./../components/common/StatusPage.vue')['default']
  }
}
